import type { Config } from "./types.ts";
import type { DataPaths } from "./paths.ts";

const HEADER =
  `# Generated by ForgeUI from config.yaml on every launch — do not edit.
# Passed to ComfyUI as --extra-model-paths-config. Folders are read-only to
# the app; missing folders are kept so Settings can flag them.
`;

/** ComfyUI's yaml format: one key per model kind, newline-separated paths. */
export function renderExtraModelPaths(config: Config): string {
  const kinds = Object.entries(config.model_folders)
    .map(([kind, folders]) =>
      [kind, folders.filter((f) => f.length > 0)] as const
    )
    .filter(([, folders]) => folders.length > 0)
    .sort(([a], [b]) => a.localeCompare(b));

  if (kinds.length === 0) return `${HEADER}forgeui: {}\n`;

  const lines = ["forgeui:"];
  for (const [kind, folders] of kinds) {
    lines.push(`  ${kind}: |-`);
    for (const folder of folders) lines.push(`    ${folder}`);
  }
  return `${HEADER}${lines.join("\n")}\n`;
}

export async function writeExtraModelPaths(
  paths: DataPaths,
  config: Config,
): Promise<string> {
  const text = renderExtraModelPaths(config);
  await Deno.writeTextFile(paths.extraModelPaths, text);
  return text;
}
