import { join } from "@std/path";
import { classOf, DIFFUSION_KINDS } from "./defaults.ts";
import type { Config } from "./types.ts";
import type { DataPaths } from "./paths.ts";

const HEADER =
  `# Generated by ForgeUI from config.yaml on every launch — do not edit.
# Passed to ComfyUI as --extra-model-paths-config. Folders are read-only to
# the app; missing folders are kept so Settings can flag them.
#
# Every diffusion-class folder is listed under both "checkpoints" and
# "diffusion_models" so a model picked from one shows up for whichever loader
# a workflow uses: ComfyUI resolves a filename against one folder key only.
`;

/**
 * Which folders end up under each ComfyUI key.
 *
 * ComfyUI resolves a loader's filename against exactly one key —
 * `UNETLoader` looks only under `diffusion_models`, `CheckpointLoaderSimple`
 * only under `checkpoints` — and it does not alias the two. ForgeUI lists
 * every model that can drive a generation in one picker, so a name from
 * `checkpoints/` can land in a `UNETLoader` and vice versa. Pooling the
 * diffusion-class folders under both keys is what makes that resolve.
 *
 * The other classes are left alone: ComfyUI already searches `unet/` under
 * `diffusion_models` and `clip/` under `text_encoders` by itself.
 */
export function resolveExtraModelPaths(
  config: Config,
  /**
   * `<appdata>/models`, where ingest files what `forge models
   * --download-model` fetched (DESIGN-MODEL-IMPORT §7.2). It is listed under
   * every kind the app knows, because a downloaded model has to resolve by
   * name for whichever loader its workflow uses — exactly like a folder the
   * user configured, which is the point: nothing downstream can tell the
   * difference.
   */
  downloads?: string | null,
): Record<string, string[]> {
  const configured: Record<string, string[]> = { ...config.model_folders };
  if (downloads) {
    for (const kind of Object.keys(configured)) {
      configured[kind] = [...(configured[kind] ?? []), join(downloads, kind)];
    }
  }
  const overrides = config.model_classes;

  const pooled: string[] = [];
  for (const kind of DIFFUSION_KINDS) {
    for (const folder of configured[kind] ?? []) {
      if (folder.length > 0 && !pooled.includes(folder)) pooled.push(folder);
    }
  }
  // A kind the user re-pointed at `diffusion` through model_classes joins the
  // pool too, so the override means the same thing here as in the picker.
  for (const [kind, folders] of Object.entries(configured)) {
    if (DIFFUSION_KINDS.includes(kind)) continue;
    if (classOf(kind, overrides) !== "diffusion") continue;
    for (const folder of folders) {
      if (folder.length > 0 && !pooled.includes(folder)) pooled.push(folder);
    }
  }

  const out: Record<string, string[]> = {};
  for (const [kind, folders] of Object.entries(configured)) {
    if (classOf(kind, overrides) === "diffusion") continue;
    const kept = folders.filter((folder) => folder.length > 0);
    if (kept.length > 0) out[kind] = kept;
  }
  if (pooled.length > 0) {
    out.checkpoints = [...pooled];
    out.diffusion_models = [...pooled];
  }
  return out;
}

/** ComfyUI's yaml format: one key per model kind, newline-separated paths. */
export function renderExtraModelPaths(
  config: Config,
  downloads?: string | null,
): string {
  const kinds = Object.entries(resolveExtraModelPaths(config, downloads))
    .sort(([a], [b]) => a.localeCompare(b));

  if (kinds.length === 0) return `${HEADER}forgeui: {}\n`;

  const lines = ["forgeui:"];
  for (const [kind, folders] of kinds) {
    lines.push(`  ${kind}: |-`);
    for (const folder of folders) lines.push(`    ${folder}`);
  }
  return `${HEADER}${lines.join("\n")}\n`;
}

export async function writeExtraModelPaths(
  paths: DataPaths,
  config: Config,
): Promise<string> {
  const text = renderExtraModelPaths(config, paths.downloads);
  await Deno.writeTextFile(paths.extraModelPaths, text);
  return text;
}
